import type { Game, GuideSection, Progress, SpoilerLevel } from '../types/guide';
import { ChecklistSection } from './ChecklistSection'; import { GuideMeta } from './GuideMeta'; import { NotesBox } from './NotesBox'; import { ProgressBar } from './ProgressBar'; import { SpoilerBlock } from './SpoilerBlock'; import { WalkthroughBlocks } from './WalkthroughBlocks';
import { lootKey, sectionKey, stepKey } from '../utils/progressKeys';
export function GuideDetail({ game, section, progress, notes, mode, onBack, onProgress, onNotes, onNext, onModeChange }: { game: Game; section: GuideSection; progress: Progress; notes: Record<string, string>; mode: SpoilerLevel; onBack: () => void; onProgress: (progress: Progress) => void; onNotes: (id: string, value: string) => void; onNext: (section: GuideSection) => void; onModeChange: (mode: SpoilerLevel) => void }) {
 const currentSectionKey = sectionKey(game.id, section.id);
 const currentStepKey = (id: string) => stepKey(game.id, section.id, id);
 const currentLootKey = (id: string) => lootKey(game.id, section.id, id);
 const completed = section.steps.filter((step) => progress.steps[currentStepKey(step.id)]).length;
 const toggleStep = (id: string) => onProgress({ ...progress, steps: { ...progress.steps, [currentStepKey(id)]: !progress.steps[currentStepKey(id)] } });
 const toggleLoot = (id: string) => onProgress({ ...progress, loot: { ...progress.loot, [currentLootKey(id)]: !progress.loot[currentLootKey(id)] } });
 const next = section.nextSectionId ? game.sections.find((item) => item.id === section.nextSectionId) : undefined;
 return <main><header><button className="back" onClick={onBack}>← {game.title}</button><label className="spoil">Spoiler mode<select value={mode} onChange={(event) => onModeChange(event.target.value as SpoilerLevel)}><option value="low">Spoiler-light</option><option value="normal">Normal</option><option value="full">Full walkthrough</option></select></label></header><article className="guide"><GuideMeta section={section}/><div className="complete"><ProgressBar completed={completed} total={section.steps.length}/><button onClick={() => onProgress({ ...progress, sections: { ...progress.sections, [currentSectionKey]: !progress.sections[currentSectionKey] } })}>{progress.sections[currentSectionKey] ? 'Completed ✓' : 'Mark section complete'}</button></div><WalkthroughBlocks blocks={section.walkthroughBlocks} mode={mode}/><ChecklistSection steps={section.steps} loot={section.loot} isStepChecked={(id) => !!progress.steps[currentStepKey(id)]} isLootChecked={(id) => !!progress.loot[currentLootKey(id)]} mode={mode} toggleStep={toggleStep} toggleLoot={toggleLoot}/>{section.boss && <SpoilerBlock level="normal" mode={mode}><section><h2>Boss guide: {section.boss.name}</h2><p><b>Weak:</b> {section.boss.weaknesses.join(', ')} · <b>Resists:</b> {section.boss.resistances.join(', ')}</p><ul>{section.boss.phases.map((phase) => <li key={phase}>{phase}</li>)}</ul><p>{section.boss.recommendedStrategy}</p></section></SpoilerBlock>}{section.missableContent.length > 0 && <section className="danger"><b>Before you advance</b><ul>{section.missableContent.map((item) => <li key={item}>{item}</li>)}</ul></section>}<SpoilerBlock level="normal" mode={mode}><section><h2>Secrets & pitfalls</h2><ul>{[...section.secrets, ...section.commonMistakes].map((item) => <li key={item}>{item}</li>)}</ul></section></SpoilerBlock><NotesBox value={notes[currentSectionKey] ?? ''} onChange={(value) => onNotes(currentSectionKey, value)}/>{next && <button className="next" onClick={() => onNext(next)}>Next guide →</button>}</article></main>;
}
