import type { GuideSection, SectionType } from '../types/guide';
export interface Filters { type: SectionType | 'All'; dlc: string; faction: string; place: string; missable: boolean; achievement: boolean; uniqueItem: boolean }
export const defaultFilters: Filters = { type: 'All', dlc: 'All', faction: 'All', place: 'All', missable: false, achievement: false, uniqueItem: false };
const values = (sections: GuideSection[], pick: (section: GuideSection) => string | undefined) => [...new Set(sections.map(pick).filter((value): value is string => Boolean(value)))].sort();
export function GuideFilters({ sections, filters, onChange }: { sections: GuideSection[]; filters: Filters; onChange: (filters: Filters) => void }) {
 const types = values(sections, (s) => s.type), dlcs = values(sections, (s) => s.dlc), factions = values(sections, (s) => s.faction), places = values(sections, (s) => s.city ?? s.region);
 const select = (key: 'type' | 'dlc' | 'faction' | 'place', value: string) => onChange({ ...filters, [key]: value });
 return <div className="filters"><select aria-label="Guide type" value={filters.type} onChange={(e) => select('type', e.target.value)}><option value="All">All types</option>{types.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="DLC" value={filters.dlc} onChange={(e) => select('dlc', e.target.value)}><option value="All">All DLC</option>{dlcs.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Faction" value={filters.faction} onChange={(e) => select('faction', e.target.value)}><option value="All">All factions</option>{factions.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Region or city" value={filters.place} onChange={(e) => select('place', e.target.value)}><option value="All">All regions/cities</option>{places.map((value) => <option key={value}>{value}</option>)}</select><label><input type="checkbox" checked={filters.missable} onChange={(e) => onChange({ ...filters, missable: e.target.checked })}/> Missable only</label><label><input type="checkbox" checked={filters.achievement} onChange={(e) => onChange({ ...filters, achievement: e.target.checked })}/> Achievements</label><label><input type="checkbox" checked={filters.uniqueItem} onChange={(e) => onChange({ ...filters, uniqueItem: e.target.checked })}/> Unique items</label></div>;
}
