import { useMemo, useState } from 'react';
import gameData from './data/games/ashen-gates.json';
const game = gameData as Game;
import type { Game, GuideSection, Progress, SectionType, SpoilerLevel } from './types/guide';
import { loadNotes, loadProgress, loadSpoiler, saveNotes, saveProgress, saveSpoiler } from './utils/storage';
import { matchesSearch } from './utils/search';
import { GameCard } from './components/GameCard'; import { SectionCard } from './components/SectionCard'; import { StepList } from './components/StepList'; import { SpoilerBlock } from './components/SpoilerBlock'; import { NotesBox } from './components/NotesBox'; import { SearchBar } from './components/SearchBar'; import { ProgressBar } from './components/ProgressBar';
const title = { low: 'Spoilerarm', normal: 'Normal', full: 'Komplettlösung' };
export default function App() {
 const [selected, setSelected] = useState<GuideSection | null>(null); const [query, setQuery] = useState(''); const [type, setType] = useState<SectionType | 'All'>('All'); const [missable, setMissable] = useState(false); const [progress, setProgress] = useState<Progress>(loadProgress); const [notes, setNotes] = useState(loadNotes); const [mode, setMode] = useState<SpoilerLevel>(loadSpoiler);
 const updateProgress = (next: Progress) => { setProgress(next); saveProgress(next); }; const updateNotes = (id: string, value: string) => { const next = { ...notes, [id]: value }; setNotes(next); saveNotes(next); };
 const sections = useMemo(() => game.sections.filter((s) => (type === 'All' || s.type === type) && (!missable || s.missable) && matchesSearch(s, query)), [query, type, missable]);
 const done = (s: GuideSection) => s.steps.filter((step) => progress.steps[step.id]).length;
 if (selected) return <main><header><button className="back" onClick={() => setSelected(null)}>← All guides</button><div className="spoil"><label>Spoiler mode<select value={mode} onChange={(e) => { const value = e.target.value as SpoilerLevel; setMode(value); saveSpoiler(value); }}>{Object.entries(title).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div></header><article className="guide"><span className="pill">{selected.type}</span>{selected.missable && <span className="warning">Missable content</span>}<h1>{selected.title}</h1><p className="sub">{selected.area} · Recommended level {selected.recommendedLevel}</p><p>{selected.objective}</p><section className="callout"><strong>Prepare:</strong> {selected.preparation}</section><div className="complete"><ProgressBar completed={done(selected)} total={selected.steps.length}/><button onClick={() => updateProgress({ ...progress, sections: { ...progress.sections, [selected.id]: !progress.sections[selected.id] } })}>{progress.sections[selected.id] ? 'Completed ✓' : 'Mark section complete'}</button></div><h2>Walkthrough</h2><StepList steps={selected.steps} checked={progress.steps} mode={mode} toggle={(id) => updateProgress({ ...progress, steps: { ...progress.steps, [id]: !progress.steps[id] } })}/>{selected.boss && <SpoilerBlock level="normal" mode={mode}><section><h2>Boss guide: {selected.boss.name}</h2><p><b>Weak:</b> {selected.boss.weaknesses.join(', ')} · <b>Resists:</b> {selected.boss.resistances.join(', ')}</p><ul>{selected.boss.phases.map((p) => <li key={p}>{p}</li>)}</ul><p>{selected.boss.recommendedStrategy}</p></section></SpoilerBlock>}<section><h2>Loot</h2>{selected.loot.map((item) => <label className="loot" key={item.id}><input type="checkbox" checked={!!progress.loot[item.id]} onChange={() => updateProgress({ ...progress, loot: { ...progress.loot, [item.id]: !progress.loot[item.id] } })}/><span><b>{item.name}</b> — {item.location} {item.missable && <em>Missable</em>}<small>{item.notes}</small></span></label>)}</section>{selected.missableContent.length > 0 && <section className="danger"><b>Before you advance</b><ul>{selected.missableContent.map((item) => <li key={item}>{item}</li>)}</ul></section>}<SpoilerBlock level="normal" mode={mode}><section><h2>Secrets & pitfalls</h2><ul>{[...selected.secrets, ...selected.commonMistakes].map((item) => <li key={item}>{item}</li>)}</ul></section></SpoilerBlock><NotesBox value={notes[selected.id] ?? ''} onChange={(value) => updateNotes(selected.id, value)} />{selected.nextSectionId && <button className="next" onClick={() => setSelected(game.sections.find((s) => s.id === selected.nextSectionId) ?? null)}>Next guide →</button>}</article></main>;
 return <main><header><div><span className="eyebrow">WALKTHROUGH COMPANION</span><h1>Your journey, organized.</h1><p>Fictional guides with the spoilers and checklists under your control.</p></div><label className="spoil">Spoiler mode<select value={mode} onChange={(e) => { const value = e.target.value as SpoilerLevel; setMode(value); saveSpoiler(value); }}>{Object.entries(title).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></header><GameCard game={game} onSelect={() => setSelected(game.sections[0])}/><section className="directory"><div className="directory-head"><h2>Guide directory</h2><SearchBar value={query} onChange={setQuery}/></div><div className="filters"><select aria-label="Guide type" value={type} onChange={(e) => setType(e.target.value as SectionType | 'All')}><option value="All">All types</option>{['Main Story','Side Quest','Boss','Area','Collectibles','Endgame'].map((x) => <option key={x}>{x}</option>)}</select><label><input type="checkbox" checked={missable} onChange={(e) => setMissable(e.target.checked)}/> Missable only</label></div><div className="grid">{sections.map((section) => <SectionCard key={section.id} section={section} done={done(section)} onOpen={() => setSelected(section)}/>)}</div>{!sections.length && <p className="empty">No guides match those filters.</p>}</section></main>;
}
